namespace cmes_webapi.Common.Resources
{
    /// <summary>
    /// enum to differentiate 2 types of error, execution time = 1 or errors that autogenerated 
    /// by not fulfilling requirements of the process flow = 2.
    /// 1=execution exception
    /// 2=generated by the bussiness because it meets some requirement
    /// </summary>
    public enum EnumErrorCode
    {

        NONE = 0,
        /// <summary>
        /// Parámetros inválidos en mensaje de entrada al servicio
        /// </summary>
        TOP0001 = 1,

        /// <summary>
        /// IPF inexistente
        /// </summary>
        TOP0002 = 2,

        /// <summary>
        /// Tipo de Operacion IPF Invalida.
        /// </summary>
        TOP0003 = 3,

        /// <summary>
        /// Operación concretada con éxito.
        /// </summary>
        TOP0200 = 200,
        /// <summary>
        /// Operación concretada con éxito. Ver mensajes adicionales.
        /// </summary>
        TOP0201 = 201,
        /// <summary>
        /// No se obtuvieron datos para la consulta realizada.
        /// </summary>
        TOP0204 = 204,

        /// <summary>
        /// El máximo de cotitulares no puede ser mayor a 3.
        /// </summary>
        TOP0205 = 205,
        /// <summary>
        /// El máximo de tasas de precanc. no puede ser mayor a 7.
        /// </summary>
        TOP0206 = 206,
        /// <summary>
        /// El certificado ya fue creado.
        /// </summary>
        TOP0207 = 207,
        /// <summary>
        /// El certificado ya fue impreso.
        /// </summary>
        TOP0208 = 208,

        /// <summary>
        /// El tipo de operatoria no existe.
        /// </summary>
        TOP0209 = 209,
        /// <summary>
        /// Excepcion no controlada.
        /// </summary>
        TOP9999 = 9999,
        /// <summary>
        /// Error al invocar servicio REST.
        /// </summary>
        TOP0300 = 300,
    }

    /// <summary>
    /// enum to differentiate 2 types of error, execution time = 1 or errors that autogenerated 
    /// by not fulfilling requirements of the process flow = 2.
    /// 1=execution exception
    /// 2=generated by the bussiness because it meets some requirement
    /// </summary>
    public enum EnumErrorType
    {
        Exception = 1,
        GeneretedException = 2
    };
}
