//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmes_webapi.Common.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCode
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CedMEP.Api.Common.Resources.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros inválidos en mensaje de entrada al servicio.
        /// </summary>
        internal static string MEP0001
        {
            get
            {
                return ResourceManager.GetString("MEP0001", resourceCulture);
            }
        }

        //Moneda invalida
        internal static string MEP0003
        {
            get
            {
                return ResourceManager.GetString("MEP0003", resourceCulture);
            }
        }

        //Codigo de Instruccion invalido
        internal static string MEP0004
        {
            get
            {
                return ResourceManager.GetString("MEP0004", resourceCulture);
            }
        }

        //La InstruccionDePago para {0} debe tener {1} campos
        internal static string MEP0005
        {
            get
            {
                return ResourceManager.GetString("MEP0005", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de operacion MEP invalida.
        /// </summary>
        internal static string MEP0006
        {
            get
            {
                return ResourceManager.GetString("MEP0006", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Operación concretada con éxito..
        /// </summary>
        internal static string MEP0200
        {
            get
            {
                return ResourceManager.GetString("MEP0200", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros inválidos en mensaje de entrada al servicio..
        /// </summary>
        internal static string MEP0002
        {
            get
            {
                return ResourceManager.GetString("MEP0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se obtuvieron datos para la consulta realizada..
        /// </summary>
        internal static string TOP0204
        {
            get
            {
                return ResourceManager.GetString("TOP0204", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Operación concretada con éxito. Ver mensajes adicionales..
        /// </summary>
        internal static string TOP0201
        {
            get
            {
                return ResourceManager.GetString("TOP0201", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Operación concretada con éxito. Ver mensajes adicionales..
        /// </summary>
        internal static string MEP0202
        {
            get
            {
                return ResourceManager.GetString("MEP0202", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Excepción no controlada.
        /// </summary>
        internal static string IPF9999
        {
            get
            {
                return ResourceManager.GetString("IPF9999", resourceCulture);
            }
        }
    }
}
