//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FN1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferenciaMEPConMovResp", Namespace="http://ws.bancogalicia.com.ar")]
    public partial class TransferenciaMEPConMovResp : object
    {
        
        private string cant_moviField;
        
        private string cuentacreField;
        
        private string cuentadeuField;
        
        private string entacreField;
        
        private string entdeuField;
        
        private string fecha_regField;
        
        private string finField;
        
        private string hostField;
        
        private string importeField;
        
        private string instrucField;
        
        private string nroField;
        
        private string obserField;
        
        private string opeField;
        
        private string suma_totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cant_movi
        {
            get
            {
                return this.cant_moviField;
            }
            set
            {
                this.cant_moviField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cuentacre
        {
            get
            {
                return this.cuentacreField;
            }
            set
            {
                this.cuentacreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cuentadeu
        {
            get
            {
                return this.cuentadeuField;
            }
            set
            {
                this.cuentadeuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string entacre
        {
            get
            {
                return this.entacreField;
            }
            set
            {
                this.entacreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string entdeu
        {
            get
            {
                return this.entdeuField;
            }
            set
            {
                this.entdeuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fecha_reg
        {
            get
            {
                return this.fecha_regField;
            }
            set
            {
                this.fecha_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fin
        {
            get
            {
                return this.finField;
            }
            set
            {
                this.finField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string instruc
        {
            get
            {
                return this.instrucField;
            }
            set
            {
                this.instrucField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nro
        {
            get
            {
                return this.nroField;
            }
            set
            {
                this.nroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string obser
        {
            get
            {
                return this.obserField;
            }
            set
            {
                this.obserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ope
        {
            get
            {
                return this.opeField;
            }
            set
            {
                this.opeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string suma_total
        {
            get
            {
                return this.suma_totalField;
            }
            set
            {
                this.suma_totalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bancogalicia.com.ar", ConfigurationName="FN1.MepEnvio")]
    public interface MepEnvio
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://ws.bancogalicia.com.ar no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        FN1.consultaMovimientosResponse consultaMovimientos(FN1.consultaMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FN1.consultaMovimientosResponse> consultaMovimientosAsync(FN1.consultaMovimientosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaMovimientosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaMovimientos", Namespace="http://ws.bancogalicia.com.ar", Order=0)]
        public FN1.consultaMovimientosRequestBody Body;
        
        public consultaMovimientosRequest()
        {
        }
        
        public consultaMovimientosRequest(FN1.consultaMovimientosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.bancogalicia.com.ar")]
    public partial class consultaMovimientosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string movimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cookie1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cookie2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cookie3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cookie4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cookie5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string version;
        
        public consultaMovimientosRequestBody()
        {
        }
        
        public consultaMovimientosRequestBody(string usuario, string clave, string movimiento, string cuenta, string mep, string cookie1, string cookie2, string cookie3, string cookie4, string cookie5, string version)
        {
            this.usuario = usuario;
            this.clave = clave;
            this.movimiento = movimiento;
            this.cuenta = cuenta;
            this.mep = mep;
            this.cookie1 = cookie1;
            this.cookie2 = cookie2;
            this.cookie3 = cookie3;
            this.cookie4 = cookie4;
            this.cookie5 = cookie5;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaMovimientosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaMovimientosResponse", Namespace="http://ws.bancogalicia.com.ar", Order=0)]
        public FN1.consultaMovimientosResponseBody Body;
        
        public consultaMovimientosResponse()
        {
        }
        
        public consultaMovimientosResponse(FN1.consultaMovimientosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.bancogalicia.com.ar")]
    public partial class consultaMovimientosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FN1.TransferenciaMEPConMovResp consultaMovimientosReturn;
        
        public consultaMovimientosResponseBody()
        {
        }
        
        public consultaMovimientosResponseBody(FN1.TransferenciaMEPConMovResp consultaMovimientosReturn)
        {
            this.consultaMovimientosReturn = consultaMovimientosReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MepEnvioChannel : FN1.MepEnvio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MepEnvioClient : System.ServiceModel.ClientBase<FN1.MepEnvio>, FN1.MepEnvio
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MepEnvioClient() : 
                base(MepEnvioClient.GetDefaultBinding(), MepEnvioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MepEnvio.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MepEnvioClient(EndpointConfiguration endpointConfiguration) : 
                base(MepEnvioClient.GetBindingForEndpoint(endpointConfiguration), MepEnvioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MepEnvioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MepEnvioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MepEnvioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MepEnvioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MepEnvioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FN1.consultaMovimientosResponse FN1.MepEnvio.consultaMovimientos(FN1.consultaMovimientosRequest request)
        {
            return base.Channel.consultaMovimientos(request);
        }
        
        public FN1.TransferenciaMEPConMovResp consultaMovimientos(string usuario, string clave, string movimiento, string cuenta, string mep, string cookie1, string cookie2, string cookie3, string cookie4, string cookie5, string version)
        {
            FN1.consultaMovimientosRequest inValue = new FN1.consultaMovimientosRequest();
            inValue.Body = new FN1.consultaMovimientosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.movimiento = movimiento;
            inValue.Body.cuenta = cuenta;
            inValue.Body.mep = mep;
            inValue.Body.cookie1 = cookie1;
            inValue.Body.cookie2 = cookie2;
            inValue.Body.cookie3 = cookie3;
            inValue.Body.cookie4 = cookie4;
            inValue.Body.cookie5 = cookie5;
            inValue.Body.version = version;
            FN1.consultaMovimientosResponse retVal = ((FN1.MepEnvio)(this)).consultaMovimientos(inValue);
            return retVal.Body.consultaMovimientosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FN1.consultaMovimientosResponse> FN1.MepEnvio.consultaMovimientosAsync(FN1.consultaMovimientosRequest request)
        {
            return base.Channel.consultaMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FN1.consultaMovimientosResponse> consultaMovimientosAsync(string usuario, string clave, string movimiento, string cuenta, string mep, string cookie1, string cookie2, string cookie3, string cookie4, string cookie5, string version)
        {
            FN1.consultaMovimientosRequest inValue = new FN1.consultaMovimientosRequest();
            inValue.Body = new FN1.consultaMovimientosRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.movimiento = movimiento;
            inValue.Body.cuenta = cuenta;
            inValue.Body.mep = mep;
            inValue.Body.cookie1 = cookie1;
            inValue.Body.cookie2 = cookie2;
            inValue.Body.cookie3 = cookie3;
            inValue.Body.cookie4 = cookie4;
            inValue.Body.cookie5 = cookie5;
            inValue.Body.version = version;
            return ((FN1.MepEnvio)(this)).consultaMovimientosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MepEnvio))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MepEnvio))
            {
                return new System.ServiceModel.EndpointAddress("http://mpstbcra.bancogalicia.com.ar/mpstbcra/services/MepEnvio");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MepEnvioClient.GetBindingForEndpoint(EndpointConfiguration.MepEnvio);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MepEnvioClient.GetEndpointAddress(EndpointConfiguration.MepEnvio);
        }
        
        public enum EndpointConfiguration
        {
            
            MepEnvio,
        }
    }
}
